"""
Generated By: Cursor (Claude Sonnet 4.5)

Pytest configuration and shared fixtures for ap-fits-headers tests.
"""

import tempfile
from pathlib import Path

import numpy as np
import pytest
from astropy.io import fits
from xisf import XISF


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_fits_file(temp_dir):
    """
    Generate a minimal FITS file for testing.

    Creates a valid FITS file with a small dummy image array.
    This avoids the need for LFS-tracked fixture files.
    """
    fits_path = temp_dir / "test.fits"

    # Create minimal FITS file with 10x10 dummy image data
    data = np.zeros((10, 10), dtype=np.float32)
    hdu = fits.PrimaryHDU(data)
    hdu.writeto(fits_path)

    return fits_path


@pytest.fixture
def sample_xisf_file(temp_dir):
    """
    Generate a minimal XISF file for testing.

    Creates a valid XISF file with a small dummy image array.
    This avoids the need for LFS-tracked fixture files.
    """
    xisf_path = temp_dir / "test.xisf"

    # Create minimal XISF file with 10x10x1 dummy image data (grayscale)
    # XISF expects 3D array: (height, width, channels)
    data = np.zeros((10, 10, 1), dtype=np.float32)
    XISF.write(str(xisf_path), data)

    return xisf_path
